// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/eldritch/scifirpg/proto/disciplines.proto

package com.eldritch.invoken.proto;

public final class Disciplines {
  private Disciplines() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code scifirpg.Discipline}
   */
  public enum Discipline
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WARFARE = 0;</code>
     *
     * <pre>
     * Determines max health
     * </pre>
     */
    WARFARE(0, 0),
    /**
     * <code>AUTOMATA = 1;</code>
     *
     * <pre>
     * Determines max hand size
     * </pre>
     */
    AUTOMATA(1, 1),
    /**
     * <code>SUBTERFUGE = 2;</code>
     *
     * <pre>
     * Determines who gets the drop on whom
     * </pre>
     */
    SUBTERFUGE(2, 2),
    /**
     * <code>CHARISMA = 3;</code>
     *
     * <pre>
     * Determines NPC predisposition towards player
     * </pre>
     */
    CHARISMA(3, 3),
    ;

    /**
     * <code>WARFARE = 0;</code>
     *
     * <pre>
     * Determines max health
     * </pre>
     */
    public static final int WARFARE_VALUE = 0;
    /**
     * <code>AUTOMATA = 1;</code>
     *
     * <pre>
     * Determines max hand size
     * </pre>
     */
    public static final int AUTOMATA_VALUE = 1;
    /**
     * <code>SUBTERFUGE = 2;</code>
     *
     * <pre>
     * Determines who gets the drop on whom
     * </pre>
     */
    public static final int SUBTERFUGE_VALUE = 2;
    /**
     * <code>CHARISMA = 3;</code>
     *
     * <pre>
     * Determines NPC predisposition towards player
     * </pre>
     */
    public static final int CHARISMA_VALUE = 3;


    public final int getNumber() { return value; }

    public static Discipline valueOf(int value) {
      switch (value) {
        case 0: return WARFARE;
        case 1: return AUTOMATA;
        case 2: return SUBTERFUGE;
        case 3: return CHARISMA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Discipline>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Discipline>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Discipline>() {
            public Discipline findValueByNumber(int number) {
              return Discipline.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Disciplines.getDescriptor().getEnumTypes().get(0);
    }

    private static final Discipline[] VALUES = values();

    public static Discipline valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Discipline(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:scifirpg.Discipline)
  }

  /**
   * Protobuf enum {@code scifirpg.Profession}
   */
  public enum Profession
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CENTURION = 0;</code>
     */
    CENTURION(0, 0),
    /**
     * <code>EXECUTOR = 1;</code>
     */
    EXECUTOR(1, 1),
    /**
     * <code>ASSASSIN = 2;</code>
     */
    ASSASSIN(2, 2),
    /**
     * <code>WARDEN = 3;</code>
     */
    WARDEN(3, 3),
    /**
     * <code>ARCHITECT = 4;</code>
     */
    ARCHITECT(4, 4),
    /**
     * <code>GHOST = 5;</code>
     */
    GHOST(5, 5),
    /**
     * <code>INQUISITOR = 6;</code>
     */
    INQUISITOR(6, 6),
    /**
     * <code>INFILTRATOR = 7;</code>
     */
    INFILTRATOR(7, 7),
    /**
     * <code>AGENT = 8;</code>
     */
    AGENT(8, 8),
    /**
     * <code>BROKER = 9;</code>
     */
    BROKER(9, 9),
    ;

    /**
     * <code>CENTURION = 0;</code>
     */
    public static final int CENTURION_VALUE = 0;
    /**
     * <code>EXECUTOR = 1;</code>
     */
    public static final int EXECUTOR_VALUE = 1;
    /**
     * <code>ASSASSIN = 2;</code>
     */
    public static final int ASSASSIN_VALUE = 2;
    /**
     * <code>WARDEN = 3;</code>
     */
    public static final int WARDEN_VALUE = 3;
    /**
     * <code>ARCHITECT = 4;</code>
     */
    public static final int ARCHITECT_VALUE = 4;
    /**
     * <code>GHOST = 5;</code>
     */
    public static final int GHOST_VALUE = 5;
    /**
     * <code>INQUISITOR = 6;</code>
     */
    public static final int INQUISITOR_VALUE = 6;
    /**
     * <code>INFILTRATOR = 7;</code>
     */
    public static final int INFILTRATOR_VALUE = 7;
    /**
     * <code>AGENT = 8;</code>
     */
    public static final int AGENT_VALUE = 8;
    /**
     * <code>BROKER = 9;</code>
     */
    public static final int BROKER_VALUE = 9;


    public final int getNumber() { return value; }

    public static Profession valueOf(int value) {
      switch (value) {
        case 0: return CENTURION;
        case 1: return EXECUTOR;
        case 2: return ASSASSIN;
        case 3: return WARDEN;
        case 4: return ARCHITECT;
        case 5: return GHOST;
        case 6: return INQUISITOR;
        case 7: return INFILTRATOR;
        case 8: return AGENT;
        case 9: return BROKER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Profession>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Profession>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Profession>() {
            public Profession findValueByNumber(int number) {
              return Profession.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Disciplines.getDescriptor().getEnumTypes().get(1);
    }

    private static final Profession[] VALUES = values();

    public static Profession valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Profession(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:scifirpg.Profession)
  }

  /**
   * Protobuf enum {@code scifirpg.AttackSubtype}
   */
  public enum AttackSubtype
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MELEE = 0;</code>
     *
     * <pre>
     * Attack - Counter
     * </pre>
     */
    MELEE(0, 0),
    /**
     * <code>RANGED = 1;</code>
     */
    RANGED(1, 1),
    /**
     * <code>HEAVY = 2;</code>
     */
    HEAVY(2, 2),
    /**
     * <code>COORDINATED = 3;</code>
     */
    COORDINATED(3, 3),
    /**
     * <code>AMBUSH = 4;</code>
     */
    AMBUSH(4, 4),
    /**
     * <code>CORRUPTION = 5;</code>
     */
    CORRUPTION(5, 5),
    ;

    /**
     * <code>MELEE = 0;</code>
     *
     * <pre>
     * Attack - Counter
     * </pre>
     */
    public static final int MELEE_VALUE = 0;
    /**
     * <code>RANGED = 1;</code>
     */
    public static final int RANGED_VALUE = 1;
    /**
     * <code>HEAVY = 2;</code>
     */
    public static final int HEAVY_VALUE = 2;
    /**
     * <code>COORDINATED = 3;</code>
     */
    public static final int COORDINATED_VALUE = 3;
    /**
     * <code>AMBUSH = 4;</code>
     */
    public static final int AMBUSH_VALUE = 4;
    /**
     * <code>CORRUPTION = 5;</code>
     */
    public static final int CORRUPTION_VALUE = 5;


    public final int getNumber() { return value; }

    public static AttackSubtype valueOf(int value) {
      switch (value) {
        case 0: return MELEE;
        case 1: return RANGED;
        case 2: return HEAVY;
        case 3: return COORDINATED;
        case 4: return AMBUSH;
        case 5: return CORRUPTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AttackSubtype>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<AttackSubtype>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AttackSubtype>() {
            public AttackSubtype findValueByNumber(int number) {
              return AttackSubtype.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Disciplines.getDescriptor().getEnumTypes().get(2);
    }

    private static final AttackSubtype[] VALUES = values();

    public static AttackSubtype valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private AttackSubtype(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:scifirpg.AttackSubtype)
  }

  /**
   * Protobuf enum {@code scifirpg.DeceiveSubtype}
   */
  public enum DeceiveSubtype
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AVOIDANCE = 0;</code>
     *
     * <pre>
     * Deceive - Reveal
     * </pre>
     */
    AVOIDANCE(0, 0),
    /**
     * <code>ROBBERY = 1;</code>
     */
    ROBBERY(1, 1),
    /**
     * <code>ESPIONAGE = 2;</code>
     */
    ESPIONAGE(2, 2),
    /**
     * <code>STALKING = 3;</code>
     */
    STALKING(3, 3),
    /**
     * <code>HACKING = 4;</code>
     */
    HACKING(4, 4),
    /**
     * <code>IMPERSONATION = 5;</code>
     */
    IMPERSONATION(5, 5),
    ;

    /**
     * <code>AVOIDANCE = 0;</code>
     *
     * <pre>
     * Deceive - Reveal
     * </pre>
     */
    public static final int AVOIDANCE_VALUE = 0;
    /**
     * <code>ROBBERY = 1;</code>
     */
    public static final int ROBBERY_VALUE = 1;
    /**
     * <code>ESPIONAGE = 2;</code>
     */
    public static final int ESPIONAGE_VALUE = 2;
    /**
     * <code>STALKING = 3;</code>
     */
    public static final int STALKING_VALUE = 3;
    /**
     * <code>HACKING = 4;</code>
     */
    public static final int HACKING_VALUE = 4;
    /**
     * <code>IMPERSONATION = 5;</code>
     */
    public static final int IMPERSONATION_VALUE = 5;


    public final int getNumber() { return value; }

    public static DeceiveSubtype valueOf(int value) {
      switch (value) {
        case 0: return AVOIDANCE;
        case 1: return ROBBERY;
        case 2: return ESPIONAGE;
        case 3: return STALKING;
        case 4: return HACKING;
        case 5: return IMPERSONATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeceiveSubtype>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeceiveSubtype>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeceiveSubtype>() {
            public DeceiveSubtype findValueByNumber(int number) {
              return DeceiveSubtype.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Disciplines.getDescriptor().getEnumTypes().get(3);
    }

    private static final DeceiveSubtype[] VALUES = values();

    public static DeceiveSubtype valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DeceiveSubtype(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:scifirpg.DeceiveSubtype)
  }

  /**
   * Protobuf enum {@code scifirpg.ExecuteSubtype}
   */
  public enum ExecuteSubtype
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ANALYSIS = 0;</code>
     *
     * <pre>
     * Execute - Interrupt
     * </pre>
     */
    ANALYSIS(0, 0),
    /**
     * <code>MANIPULATION = 1;</code>
     */
    MANIPULATION(1, 1),
    /**
     * <code>CREATION = 2;</code>
     */
    CREATION(2, 2),
    /**
     * <code>UPGRADE = 3;</code>
     */
    UPGRADE(3, 3),
    /**
     * <code>ILLUSION = 4;</code>
     */
    ILLUSION(4, 4),
    /**
     * <code>EMPATHY = 5;</code>
     */
    EMPATHY(5, 5),
    ;

    /**
     * <code>ANALYSIS = 0;</code>
     *
     * <pre>
     * Execute - Interrupt
     * </pre>
     */
    public static final int ANALYSIS_VALUE = 0;
    /**
     * <code>MANIPULATION = 1;</code>
     */
    public static final int MANIPULATION_VALUE = 1;
    /**
     * <code>CREATION = 2;</code>
     */
    public static final int CREATION_VALUE = 2;
    /**
     * <code>UPGRADE = 3;</code>
     */
    public static final int UPGRADE_VALUE = 3;
    /**
     * <code>ILLUSION = 4;</code>
     */
    public static final int ILLUSION_VALUE = 4;
    /**
     * <code>EMPATHY = 5;</code>
     */
    public static final int EMPATHY_VALUE = 5;


    public final int getNumber() { return value; }

    public static ExecuteSubtype valueOf(int value) {
      switch (value) {
        case 0: return ANALYSIS;
        case 1: return MANIPULATION;
        case 2: return CREATION;
        case 3: return UPGRADE;
        case 4: return ILLUSION;
        case 5: return EMPATHY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExecuteSubtype>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ExecuteSubtype>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExecuteSubtype>() {
            public ExecuteSubtype findValueByNumber(int number) {
              return ExecuteSubtype.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Disciplines.getDescriptor().getEnumTypes().get(4);
    }

    private static final ExecuteSubtype[] VALUES = values();

    public static ExecuteSubtype valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ExecuteSubtype(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:scifirpg.ExecuteSubtype)
  }

  /**
   * Protobuf enum {@code scifirpg.Influence}
   */
  public enum Influence
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PERSUASION = 0;</code>
     *
     * <pre>
     * Dialogue
     * </pre>
     */
    PERSUASION(0, 0),
    /**
     * <code>BRIBERY = 1;</code>
     */
    BRIBERY(1, 1),
    /**
     * <code>SEDUCTION = 2;</code>
     */
    SEDUCTION(2, 2),
    /**
     * <code>DEMAGOGY = 3;</code>
     */
    DEMAGOGY(3, 3),
    /**
     * <code>INTIMIDATION = 4;</code>
     */
    INTIMIDATION(4, 4),
    /**
     * <code>BLUFFING = 5;</code>
     */
    BLUFFING(5, 5),
    /**
     * <code>DOMINATION = 6;</code>
     */
    DOMINATION(6, 6),
    ;

    /**
     * <code>PERSUASION = 0;</code>
     *
     * <pre>
     * Dialogue
     * </pre>
     */
    public static final int PERSUASION_VALUE = 0;
    /**
     * <code>BRIBERY = 1;</code>
     */
    public static final int BRIBERY_VALUE = 1;
    /**
     * <code>SEDUCTION = 2;</code>
     */
    public static final int SEDUCTION_VALUE = 2;
    /**
     * <code>DEMAGOGY = 3;</code>
     */
    public static final int DEMAGOGY_VALUE = 3;
    /**
     * <code>INTIMIDATION = 4;</code>
     */
    public static final int INTIMIDATION_VALUE = 4;
    /**
     * <code>BLUFFING = 5;</code>
     */
    public static final int BLUFFING_VALUE = 5;
    /**
     * <code>DOMINATION = 6;</code>
     */
    public static final int DOMINATION_VALUE = 6;


    public final int getNumber() { return value; }

    public static Influence valueOf(int value) {
      switch (value) {
        case 0: return PERSUASION;
        case 1: return BRIBERY;
        case 2: return SEDUCTION;
        case 3: return DEMAGOGY;
        case 4: return INTIMIDATION;
        case 5: return BLUFFING;
        case 6: return DOMINATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Influence>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Influence>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Influence>() {
            public Influence findValueByNumber(int number) {
              return Influence.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Disciplines.getDescriptor().getEnumTypes().get(5);
    }

    private static final Influence[] VALUES = values();

    public static Influence valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Influence(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:scifirpg.Influence)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-com/eldritch/scifirpg/proto/discipline" +
      "s.proto\022\010scifirpg*E\n\nDiscipline\022\013\n\007WARFA" +
      "RE\020\000\022\014\n\010AUTOMATA\020\001\022\016\n\nSUBTERFUGE\020\002\022\014\n\010CH" +
      "ARISMA\020\003*\225\001\n\nProfession\022\r\n\tCENTURION\020\000\022\014" +
      "\n\010EXECUTOR\020\001\022\014\n\010ASSASSIN\020\002\022\n\n\006WARDEN\020\003\022\r" +
      "\n\tARCHITECT\020\004\022\t\n\005GHOST\020\005\022\016\n\nINQUISITOR\020\006" +
      "\022\017\n\013INFILTRATOR\020\007\022\t\n\005AGENT\020\010\022\n\n\006BROKER\020\t" +
      "*^\n\rAttackSubtype\022\t\n\005MELEE\020\000\022\n\n\006RANGED\020\001" +
      "\022\t\n\005HEAVY\020\002\022\017\n\013COORDINATED\020\003\022\n\n\006AMBUSH\020\004" +
      "\022\016\n\nCORRUPTION\020\005*i\n\016DeceiveSubtype\022\r\n\tAV",
      "OIDANCE\020\000\022\013\n\007ROBBERY\020\001\022\r\n\tESPIONAGE\020\002\022\014\n" +
      "\010STALKING\020\003\022\013\n\007HACKING\020\004\022\021\n\rIMPERSONATIO" +
      "N\020\005*f\n\016ExecuteSubtype\022\014\n\010ANALYSIS\020\000\022\020\n\014M" +
      "ANIPULATION\020\001\022\014\n\010CREATION\020\002\022\013\n\007UPGRADE\020\003" +
      "\022\014\n\010ILLUSION\020\004\022\013\n\007EMPATHY\020\005*u\n\tInfluence" +
      "\022\016\n\nPERSUASION\020\000\022\013\n\007BRIBERY\020\001\022\r\n\tSEDUCTI" +
      "ON\020\002\022\014\n\010DEMAGOGY\020\003\022\020\n\014INTIMIDATION\020\004\022\014\n\010" +
      "BLUFFING\020\005\022\016\n\nDOMINATION\020\006B\035\n\033com.eldrit" +
      "ch.scifirpg.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
