// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/eldritch/invoken/proto/factions.proto

package com.eldritch.invoken.proto;

public final class Factions {
  private Factions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FactionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .scifirpg.Faction.Relation relation = 3;
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    java.util.List<com.eldritch.invoken.proto.Factions.Faction.Relation> 
        getRelationList();
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    com.eldritch.invoken.proto.Factions.Faction.Relation getRelation(int index);
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    int getRelationCount();
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    java.util.List<? extends com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder> 
        getRelationOrBuilderList();
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder getRelationOrBuilder(
        int index);

    // repeated .scifirpg.Faction.Rank rank = 4;
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    java.util.List<com.eldritch.invoken.proto.Factions.Faction.Rank> 
        getRankList();
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    com.eldritch.invoken.proto.Factions.Faction.Rank getRank(int index);
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    int getRankCount();
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    java.util.List<? extends com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder> 
        getRankOrBuilderList();
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder getRankOrBuilder(
        int index);

    // optional .scifirpg.Profession alignment = 5;
    /**
     * <code>optional .scifirpg.Profession alignment = 5;</code>
     */
    boolean hasAlignment();
    /**
     * <code>optional .scifirpg.Profession alignment = 5;</code>
     */
    com.eldritch.invoken.proto.Disciplines.Profession getAlignment();

    // optional bool visible = 6 [default = false];
    /**
     * <code>optional bool visible = 6 [default = false];</code>
     */
    boolean hasVisible();
    /**
     * <code>optional bool visible = 6 [default = false];</code>
     */
    boolean getVisible();
  }
  /**
   * Protobuf type {@code scifirpg.Faction}
   */
  public static final class Faction extends
      com.google.protobuf.GeneratedMessage
      implements FactionOrBuilder {
    // Use Faction.newBuilder() to construct.
    private Faction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Faction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Faction defaultInstance;
    public static Faction getDefaultInstance() {
      return defaultInstance;
    }

    public Faction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Faction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                relation_ = new java.util.ArrayList<com.eldritch.invoken.proto.Factions.Faction.Relation>();
                mutable_bitField0_ |= 0x00000004;
              }
              relation_.add(input.readMessage(com.eldritch.invoken.proto.Factions.Faction.Relation.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                rank_ = new java.util.ArrayList<com.eldritch.invoken.proto.Factions.Faction.Rank>();
                mutable_bitField0_ |= 0x00000008;
              }
              rank_.add(input.readMessage(com.eldritch.invoken.proto.Factions.Faction.Rank.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.eldritch.invoken.proto.Disciplines.Profession value = com.eldritch.invoken.proto.Disciplines.Profession.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                alignment_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              visible_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          relation_ = java.util.Collections.unmodifiableList(relation_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          rank_ = java.util.Collections.unmodifiableList(rank_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eldritch.invoken.proto.Factions.Faction.class, com.eldritch.invoken.proto.Factions.Faction.Builder.class);
    }

    public static com.google.protobuf.Parser<Faction> PARSER =
        new com.google.protobuf.AbstractParser<Faction>() {
      public Faction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Faction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Faction> getParserForType() {
      return PARSER;
    }

    public interface RelationOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string faction_id = 1;
      /**
       * <code>optional string faction_id = 1;</code>
       *
       * <pre>
       * OPTIONAL: might change to int32
       * </pre>
       */
      boolean hasFactionId();
      /**
       * <code>optional string faction_id = 1;</code>
       *
       * <pre>
       * OPTIONAL: might change to int32
       * </pre>
       */
      java.lang.String getFactionId();
      /**
       * <code>optional string faction_id = 1;</code>
       *
       * <pre>
       * OPTIONAL: might change to int32
       * </pre>
       */
      com.google.protobuf.ByteString
          getFactionIdBytes();

      // optional int32 reaction = 2;
      /**
       * <code>optional int32 reaction = 2;</code>
       *
       * <pre>
       * positive good, negative bad
       * </pre>
       */
      boolean hasReaction();
      /**
       * <code>optional int32 reaction = 2;</code>
       *
       * <pre>
       * positive good, negative bad
       * </pre>
       */
      int getReaction();
    }
    /**
     * Protobuf type {@code scifirpg.Faction.Relation}
     */
    public static final class Relation extends
        com.google.protobuf.GeneratedMessage
        implements RelationOrBuilder {
      // Use Relation.newBuilder() to construct.
      private Relation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Relation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Relation defaultInstance;
      public static Relation getDefaultInstance() {
        return defaultInstance;
      }

      public Relation getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Relation(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                factionId_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                reaction_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Relation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Relation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eldritch.invoken.proto.Factions.Faction.Relation.class, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder.class);
      }

      public static com.google.protobuf.Parser<Relation> PARSER =
          new com.google.protobuf.AbstractParser<Relation>() {
        public Relation parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Relation(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Relation> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string faction_id = 1;
      public static final int FACTION_ID_FIELD_NUMBER = 1;
      private java.lang.Object factionId_;
      /**
       * <code>optional string faction_id = 1;</code>
       *
       * <pre>
       * OPTIONAL: might change to int32
       * </pre>
       */
      public boolean hasFactionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string faction_id = 1;</code>
       *
       * <pre>
       * OPTIONAL: might change to int32
       * </pre>
       */
      public java.lang.String getFactionId() {
        java.lang.Object ref = factionId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            factionId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string faction_id = 1;</code>
       *
       * <pre>
       * OPTIONAL: might change to int32
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFactionIdBytes() {
        java.lang.Object ref = factionId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          factionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 reaction = 2;
      public static final int REACTION_FIELD_NUMBER = 2;
      private int reaction_;
      /**
       * <code>optional int32 reaction = 2;</code>
       *
       * <pre>
       * positive good, negative bad
       * </pre>
       */
      public boolean hasReaction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 reaction = 2;</code>
       *
       * <pre>
       * positive good, negative bad
       * </pre>
       */
      public int getReaction() {
        return reaction_;
      }

      private void initFields() {
        factionId_ = "";
        reaction_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getFactionIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, reaction_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getFactionIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, reaction_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Relation parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.eldritch.invoken.proto.Factions.Faction.Relation prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code scifirpg.Faction.Relation}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Relation_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Relation_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.eldritch.invoken.proto.Factions.Faction.Relation.class, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder.class);
        }

        // Construct using com.eldritch.invoken.proto.Factions.Faction.Relation.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          factionId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          reaction_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Relation_descriptor;
        }

        public com.eldritch.invoken.proto.Factions.Faction.Relation getDefaultInstanceForType() {
          return com.eldritch.invoken.proto.Factions.Faction.Relation.getDefaultInstance();
        }

        public com.eldritch.invoken.proto.Factions.Faction.Relation build() {
          com.eldritch.invoken.proto.Factions.Faction.Relation result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.eldritch.invoken.proto.Factions.Faction.Relation buildPartial() {
          com.eldritch.invoken.proto.Factions.Faction.Relation result = new com.eldritch.invoken.proto.Factions.Faction.Relation(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.factionId_ = factionId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.reaction_ = reaction_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.eldritch.invoken.proto.Factions.Faction.Relation) {
            return mergeFrom((com.eldritch.invoken.proto.Factions.Faction.Relation)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.eldritch.invoken.proto.Factions.Faction.Relation other) {
          if (other == com.eldritch.invoken.proto.Factions.Faction.Relation.getDefaultInstance()) return this;
          if (other.hasFactionId()) {
            bitField0_ |= 0x00000001;
            factionId_ = other.factionId_;
            onChanged();
          }
          if (other.hasReaction()) {
            setReaction(other.getReaction());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.eldritch.invoken.proto.Factions.Faction.Relation parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.eldritch.invoken.proto.Factions.Faction.Relation) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string faction_id = 1;
        private java.lang.Object factionId_ = "";
        /**
         * <code>optional string faction_id = 1;</code>
         *
         * <pre>
         * OPTIONAL: might change to int32
         * </pre>
         */
        public boolean hasFactionId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string faction_id = 1;</code>
         *
         * <pre>
         * OPTIONAL: might change to int32
         * </pre>
         */
        public java.lang.String getFactionId() {
          java.lang.Object ref = factionId_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            factionId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string faction_id = 1;</code>
         *
         * <pre>
         * OPTIONAL: might change to int32
         * </pre>
         */
        public com.google.protobuf.ByteString
            getFactionIdBytes() {
          java.lang.Object ref = factionId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            factionId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string faction_id = 1;</code>
         *
         * <pre>
         * OPTIONAL: might change to int32
         * </pre>
         */
        public Builder setFactionId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          factionId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string faction_id = 1;</code>
         *
         * <pre>
         * OPTIONAL: might change to int32
         * </pre>
         */
        public Builder clearFactionId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          factionId_ = getDefaultInstance().getFactionId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string faction_id = 1;</code>
         *
         * <pre>
         * OPTIONAL: might change to int32
         * </pre>
         */
        public Builder setFactionIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          factionId_ = value;
          onChanged();
          return this;
        }

        // optional int32 reaction = 2;
        private int reaction_ ;
        /**
         * <code>optional int32 reaction = 2;</code>
         *
         * <pre>
         * positive good, negative bad
         * </pre>
         */
        public boolean hasReaction() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 reaction = 2;</code>
         *
         * <pre>
         * positive good, negative bad
         * </pre>
         */
        public int getReaction() {
          return reaction_;
        }
        /**
         * <code>optional int32 reaction = 2;</code>
         *
         * <pre>
         * positive good, negative bad
         * </pre>
         */
        public Builder setReaction(int value) {
          bitField0_ |= 0x00000002;
          reaction_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 reaction = 2;</code>
         *
         * <pre>
         * positive good, negative bad
         * </pre>
         */
        public Builder clearReaction() {
          bitField0_ = (bitField0_ & ~0x00000002);
          reaction_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:scifirpg.Faction.Relation)
      }

      static {
        defaultInstance = new Relation(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:scifirpg.Faction.Relation)
    }

    public interface RankOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 id = 1;
      /**
       * <code>required int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 1;</code>
       */
      int getId();

      // required string title = 2;
      /**
       * <code>required string title = 2;</code>
       */
      boolean hasTitle();
      /**
       * <code>required string title = 2;</code>
       */
      java.lang.String getTitle();
      /**
       * <code>required string title = 2;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();
    }
    /**
     * Protobuf type {@code scifirpg.Faction.Rank}
     */
    public static final class Rank extends
        com.google.protobuf.GeneratedMessage
        implements RankOrBuilder {
      // Use Rank.newBuilder() to construct.
      private Rank(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Rank(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Rank defaultInstance;
      public static Rank getDefaultInstance() {
        return defaultInstance;
      }

      public Rank getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Rank(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                title_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Rank_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Rank_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eldritch.invoken.proto.Factions.Faction.Rank.class, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder.class);
      }

      public static com.google.protobuf.Parser<Rank> PARSER =
          new com.google.protobuf.AbstractParser<Rank>() {
        public Rank parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Rank(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Rank> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      // required string title = 2;
      public static final int TITLE_FIELD_NUMBER = 2;
      private java.lang.Object title_;
      /**
       * <code>required string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        id_ = 0;
        title_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTitle()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTitleBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTitleBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.eldritch.invoken.proto.Factions.Faction.Rank parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.eldritch.invoken.proto.Factions.Faction.Rank prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code scifirpg.Faction.Rank}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Rank_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Rank_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.eldritch.invoken.proto.Factions.Faction.Rank.class, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder.class);
        }

        // Construct using com.eldritch.invoken.proto.Factions.Faction.Rank.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_Rank_descriptor;
        }

        public com.eldritch.invoken.proto.Factions.Faction.Rank getDefaultInstanceForType() {
          return com.eldritch.invoken.proto.Factions.Faction.Rank.getDefaultInstance();
        }

        public com.eldritch.invoken.proto.Factions.Faction.Rank build() {
          com.eldritch.invoken.proto.Factions.Faction.Rank result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.eldritch.invoken.proto.Factions.Faction.Rank buildPartial() {
          com.eldritch.invoken.proto.Factions.Faction.Rank result = new com.eldritch.invoken.proto.Factions.Faction.Rank(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.title_ = title_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.eldritch.invoken.proto.Factions.Faction.Rank) {
            return mergeFrom((com.eldritch.invoken.proto.Factions.Faction.Rank)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.eldritch.invoken.proto.Factions.Faction.Rank other) {
          if (other == com.eldritch.invoken.proto.Factions.Faction.Rank.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasTitle()) {
            bitField0_ |= 0x00000002;
            title_ = other.title_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasTitle()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.eldritch.invoken.proto.Factions.Faction.Rank parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.eldritch.invoken.proto.Factions.Faction.Rank) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 id = 1;
        private int id_ ;
        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        // required string title = 2;
        private java.lang.Object title_ = "";
        /**
         * <code>required string title = 2;</code>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string title = 2;</code>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string title = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string title = 2;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string title = 2;</code>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>required string title = 2;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:scifirpg.Faction.Rank)
      }

      static {
        defaultInstance = new Rank(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:scifirpg.Faction.Rank)
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .scifirpg.Faction.Relation relation = 3;
    public static final int RELATION_FIELD_NUMBER = 3;
    private java.util.List<com.eldritch.invoken.proto.Factions.Faction.Relation> relation_;
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    public java.util.List<com.eldritch.invoken.proto.Factions.Faction.Relation> getRelationList() {
      return relation_;
    }
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    public java.util.List<? extends com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder> 
        getRelationOrBuilderList() {
      return relation_;
    }
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    public int getRelationCount() {
      return relation_.size();
    }
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    public com.eldritch.invoken.proto.Factions.Faction.Relation getRelation(int index) {
      return relation_.get(index);
    }
    /**
     * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
     */
    public com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder getRelationOrBuilder(
        int index) {
      return relation_.get(index);
    }

    // repeated .scifirpg.Faction.Rank rank = 4;
    public static final int RANK_FIELD_NUMBER = 4;
    private java.util.List<com.eldritch.invoken.proto.Factions.Faction.Rank> rank_;
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    public java.util.List<com.eldritch.invoken.proto.Factions.Faction.Rank> getRankList() {
      return rank_;
    }
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    public java.util.List<? extends com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder> 
        getRankOrBuilderList() {
      return rank_;
    }
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    public int getRankCount() {
      return rank_.size();
    }
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    public com.eldritch.invoken.proto.Factions.Faction.Rank getRank(int index) {
      return rank_.get(index);
    }
    /**
     * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
     */
    public com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder getRankOrBuilder(
        int index) {
      return rank_.get(index);
    }

    // optional .scifirpg.Profession alignment = 5;
    public static final int ALIGNMENT_FIELD_NUMBER = 5;
    private com.eldritch.invoken.proto.Disciplines.Profession alignment_;
    /**
     * <code>optional .scifirpg.Profession alignment = 5;</code>
     */
    public boolean hasAlignment() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .scifirpg.Profession alignment = 5;</code>
     */
    public com.eldritch.invoken.proto.Disciplines.Profession getAlignment() {
      return alignment_;
    }

    // optional bool visible = 6 [default = false];
    public static final int VISIBLE_FIELD_NUMBER = 6;
    private boolean visible_;
    /**
     * <code>optional bool visible = 6 [default = false];</code>
     */
    public boolean hasVisible() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool visible = 6 [default = false];</code>
     */
    public boolean getVisible() {
      return visible_;
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      relation_ = java.util.Collections.emptyList();
      rank_ = java.util.Collections.emptyList();
      alignment_ = com.eldritch.invoken.proto.Disciplines.Profession.CENTURION;
      visible_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRankCount(); i++) {
        if (!getRank(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < relation_.size(); i++) {
        output.writeMessage(3, relation_.get(i));
      }
      for (int i = 0; i < rank_.size(); i++) {
        output.writeMessage(4, rank_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(5, alignment_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(6, visible_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < relation_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, relation_.get(i));
      }
      for (int i = 0; i < rank_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, rank_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, alignment_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, visible_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eldritch.invoken.proto.Factions.Faction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eldritch.invoken.proto.Factions.Faction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scifirpg.Faction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eldritch.invoken.proto.Factions.FactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eldritch.invoken.proto.Factions.Faction.class, com.eldritch.invoken.proto.Factions.Faction.Builder.class);
      }

      // Construct using com.eldritch.invoken.proto.Factions.Faction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRelationFieldBuilder();
          getRankFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (relationBuilder_ == null) {
          relation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          relationBuilder_.clear();
        }
        if (rankBuilder_ == null) {
          rank_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          rankBuilder_.clear();
        }
        alignment_ = com.eldritch.invoken.proto.Disciplines.Profession.CENTURION;
        bitField0_ = (bitField0_ & ~0x00000010);
        visible_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eldritch.invoken.proto.Factions.internal_static_scifirpg_Faction_descriptor;
      }

      public com.eldritch.invoken.proto.Factions.Faction getDefaultInstanceForType() {
        return com.eldritch.invoken.proto.Factions.Faction.getDefaultInstance();
      }

      public com.eldritch.invoken.proto.Factions.Faction build() {
        com.eldritch.invoken.proto.Factions.Faction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eldritch.invoken.proto.Factions.Faction buildPartial() {
        com.eldritch.invoken.proto.Factions.Faction result = new com.eldritch.invoken.proto.Factions.Faction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (relationBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            relation_ = java.util.Collections.unmodifiableList(relation_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.relation_ = relation_;
        } else {
          result.relation_ = relationBuilder_.build();
        }
        if (rankBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            rank_ = java.util.Collections.unmodifiableList(rank_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.rank_ = rank_;
        } else {
          result.rank_ = rankBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.alignment_ = alignment_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.visible_ = visible_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eldritch.invoken.proto.Factions.Faction) {
          return mergeFrom((com.eldritch.invoken.proto.Factions.Faction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eldritch.invoken.proto.Factions.Faction other) {
        if (other == com.eldritch.invoken.proto.Factions.Faction.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (relationBuilder_ == null) {
          if (!other.relation_.isEmpty()) {
            if (relation_.isEmpty()) {
              relation_ = other.relation_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRelationIsMutable();
              relation_.addAll(other.relation_);
            }
            onChanged();
          }
        } else {
          if (!other.relation_.isEmpty()) {
            if (relationBuilder_.isEmpty()) {
              relationBuilder_.dispose();
              relationBuilder_ = null;
              relation_ = other.relation_;
              bitField0_ = (bitField0_ & ~0x00000004);
              relationBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRelationFieldBuilder() : null;
            } else {
              relationBuilder_.addAllMessages(other.relation_);
            }
          }
        }
        if (rankBuilder_ == null) {
          if (!other.rank_.isEmpty()) {
            if (rank_.isEmpty()) {
              rank_ = other.rank_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRankIsMutable();
              rank_.addAll(other.rank_);
            }
            onChanged();
          }
        } else {
          if (!other.rank_.isEmpty()) {
            if (rankBuilder_.isEmpty()) {
              rankBuilder_.dispose();
              rankBuilder_ = null;
              rank_ = other.rank_;
              bitField0_ = (bitField0_ & ~0x00000008);
              rankBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRankFieldBuilder() : null;
            } else {
              rankBuilder_.addAllMessages(other.rank_);
            }
          }
        }
        if (other.hasAlignment()) {
          setAlignment(other.getAlignment());
        }
        if (other.hasVisible()) {
          setVisible(other.getVisible());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getRankCount(); i++) {
          if (!getRank(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eldritch.invoken.proto.Factions.Faction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eldritch.invoken.proto.Factions.Faction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .scifirpg.Faction.Relation relation = 3;
      private java.util.List<com.eldritch.invoken.proto.Factions.Faction.Relation> relation_ =
        java.util.Collections.emptyList();
      private void ensureRelationIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          relation_ = new java.util.ArrayList<com.eldritch.invoken.proto.Factions.Faction.Relation>(relation_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.eldritch.invoken.proto.Factions.Faction.Relation, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder, com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder> relationBuilder_;

      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public java.util.List<com.eldritch.invoken.proto.Factions.Faction.Relation> getRelationList() {
        if (relationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(relation_);
        } else {
          return relationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public int getRelationCount() {
        if (relationBuilder_ == null) {
          return relation_.size();
        } else {
          return relationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Relation getRelation(int index) {
        if (relationBuilder_ == null) {
          return relation_.get(index);
        } else {
          return relationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder setRelation(
          int index, com.eldritch.invoken.proto.Factions.Faction.Relation value) {
        if (relationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationIsMutable();
          relation_.set(index, value);
          onChanged();
        } else {
          relationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder setRelation(
          int index, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder builderForValue) {
        if (relationBuilder_ == null) {
          ensureRelationIsMutable();
          relation_.set(index, builderForValue.build());
          onChanged();
        } else {
          relationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder addRelation(com.eldritch.invoken.proto.Factions.Faction.Relation value) {
        if (relationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationIsMutable();
          relation_.add(value);
          onChanged();
        } else {
          relationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder addRelation(
          int index, com.eldritch.invoken.proto.Factions.Faction.Relation value) {
        if (relationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationIsMutable();
          relation_.add(index, value);
          onChanged();
        } else {
          relationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder addRelation(
          com.eldritch.invoken.proto.Factions.Faction.Relation.Builder builderForValue) {
        if (relationBuilder_ == null) {
          ensureRelationIsMutable();
          relation_.add(builderForValue.build());
          onChanged();
        } else {
          relationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder addRelation(
          int index, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder builderForValue) {
        if (relationBuilder_ == null) {
          ensureRelationIsMutable();
          relation_.add(index, builderForValue.build());
          onChanged();
        } else {
          relationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder addAllRelation(
          java.lang.Iterable<? extends com.eldritch.invoken.proto.Factions.Faction.Relation> values) {
        if (relationBuilder_ == null) {
          ensureRelationIsMutable();
          super.addAll(values, relation_);
          onChanged();
        } else {
          relationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder clearRelation() {
        if (relationBuilder_ == null) {
          relation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          relationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public Builder removeRelation(int index) {
        if (relationBuilder_ == null) {
          ensureRelationIsMutable();
          relation_.remove(index);
          onChanged();
        } else {
          relationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Relation.Builder getRelationBuilder(
          int index) {
        return getRelationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder getRelationOrBuilder(
          int index) {
        if (relationBuilder_ == null) {
          return relation_.get(index);  } else {
          return relationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public java.util.List<? extends com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder> 
           getRelationOrBuilderList() {
        if (relationBuilder_ != null) {
          return relationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(relation_);
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Relation.Builder addRelationBuilder() {
        return getRelationFieldBuilder().addBuilder(
            com.eldritch.invoken.proto.Factions.Faction.Relation.getDefaultInstance());
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Relation.Builder addRelationBuilder(
          int index) {
        return getRelationFieldBuilder().addBuilder(
            index, com.eldritch.invoken.proto.Factions.Faction.Relation.getDefaultInstance());
      }
      /**
       * <code>repeated .scifirpg.Faction.Relation relation = 3;</code>
       */
      public java.util.List<com.eldritch.invoken.proto.Factions.Faction.Relation.Builder> 
           getRelationBuilderList() {
        return getRelationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.eldritch.invoken.proto.Factions.Faction.Relation, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder, com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder> 
          getRelationFieldBuilder() {
        if (relationBuilder_ == null) {
          relationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.eldritch.invoken.proto.Factions.Faction.Relation, com.eldritch.invoken.proto.Factions.Faction.Relation.Builder, com.eldritch.invoken.proto.Factions.Faction.RelationOrBuilder>(
                  relation_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          relation_ = null;
        }
        return relationBuilder_;
      }

      // repeated .scifirpg.Faction.Rank rank = 4;
      private java.util.List<com.eldritch.invoken.proto.Factions.Faction.Rank> rank_ =
        java.util.Collections.emptyList();
      private void ensureRankIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          rank_ = new java.util.ArrayList<com.eldritch.invoken.proto.Factions.Faction.Rank>(rank_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.eldritch.invoken.proto.Factions.Faction.Rank, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder, com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder> rankBuilder_;

      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public java.util.List<com.eldritch.invoken.proto.Factions.Faction.Rank> getRankList() {
        if (rankBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rank_);
        } else {
          return rankBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public int getRankCount() {
        if (rankBuilder_ == null) {
          return rank_.size();
        } else {
          return rankBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Rank getRank(int index) {
        if (rankBuilder_ == null) {
          return rank_.get(index);
        } else {
          return rankBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder setRank(
          int index, com.eldritch.invoken.proto.Factions.Faction.Rank value) {
        if (rankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankIsMutable();
          rank_.set(index, value);
          onChanged();
        } else {
          rankBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder setRank(
          int index, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder builderForValue) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder addRank(com.eldritch.invoken.proto.Factions.Faction.Rank value) {
        if (rankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankIsMutable();
          rank_.add(value);
          onChanged();
        } else {
          rankBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder addRank(
          int index, com.eldritch.invoken.proto.Factions.Faction.Rank value) {
        if (rankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankIsMutable();
          rank_.add(index, value);
          onChanged();
        } else {
          rankBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder addRank(
          com.eldritch.invoken.proto.Factions.Faction.Rank.Builder builderForValue) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.add(builderForValue.build());
          onChanged();
        } else {
          rankBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder addRank(
          int index, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder builderForValue) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder addAllRank(
          java.lang.Iterable<? extends com.eldritch.invoken.proto.Factions.Faction.Rank> values) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          super.addAll(values, rank_);
          onChanged();
        } else {
          rankBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder clearRank() {
        if (rankBuilder_ == null) {
          rank_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          rankBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public Builder removeRank(int index) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.remove(index);
          onChanged();
        } else {
          rankBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Rank.Builder getRankBuilder(
          int index) {
        return getRankFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder getRankOrBuilder(
          int index) {
        if (rankBuilder_ == null) {
          return rank_.get(index);  } else {
          return rankBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public java.util.List<? extends com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder> 
           getRankOrBuilderList() {
        if (rankBuilder_ != null) {
          return rankBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rank_);
        }
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Rank.Builder addRankBuilder() {
        return getRankFieldBuilder().addBuilder(
            com.eldritch.invoken.proto.Factions.Faction.Rank.getDefaultInstance());
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public com.eldritch.invoken.proto.Factions.Faction.Rank.Builder addRankBuilder(
          int index) {
        return getRankFieldBuilder().addBuilder(
            index, com.eldritch.invoken.proto.Factions.Faction.Rank.getDefaultInstance());
      }
      /**
       * <code>repeated .scifirpg.Faction.Rank rank = 4;</code>
       */
      public java.util.List<com.eldritch.invoken.proto.Factions.Faction.Rank.Builder> 
           getRankBuilderList() {
        return getRankFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.eldritch.invoken.proto.Factions.Faction.Rank, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder, com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder> 
          getRankFieldBuilder() {
        if (rankBuilder_ == null) {
          rankBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.eldritch.invoken.proto.Factions.Faction.Rank, com.eldritch.invoken.proto.Factions.Faction.Rank.Builder, com.eldritch.invoken.proto.Factions.Faction.RankOrBuilder>(
                  rank_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          rank_ = null;
        }
        return rankBuilder_;
      }

      // optional .scifirpg.Profession alignment = 5;
      private com.eldritch.invoken.proto.Disciplines.Profession alignment_ = com.eldritch.invoken.proto.Disciplines.Profession.CENTURION;
      /**
       * <code>optional .scifirpg.Profession alignment = 5;</code>
       */
      public boolean hasAlignment() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .scifirpg.Profession alignment = 5;</code>
       */
      public com.eldritch.invoken.proto.Disciplines.Profession getAlignment() {
        return alignment_;
      }
      /**
       * <code>optional .scifirpg.Profession alignment = 5;</code>
       */
      public Builder setAlignment(com.eldritch.invoken.proto.Disciplines.Profession value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        alignment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .scifirpg.Profession alignment = 5;</code>
       */
      public Builder clearAlignment() {
        bitField0_ = (bitField0_ & ~0x00000010);
        alignment_ = com.eldritch.invoken.proto.Disciplines.Profession.CENTURION;
        onChanged();
        return this;
      }

      // optional bool visible = 6 [default = false];
      private boolean visible_ ;
      /**
       * <code>optional bool visible = 6 [default = false];</code>
       */
      public boolean hasVisible() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool visible = 6 [default = false];</code>
       */
      public boolean getVisible() {
        return visible_;
      }
      /**
       * <code>optional bool visible = 6 [default = false];</code>
       */
      public Builder setVisible(boolean value) {
        bitField0_ |= 0x00000020;
        visible_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool visible = 6 [default = false];</code>
       */
      public Builder clearVisible() {
        bitField0_ = (bitField0_ & ~0x00000020);
        visible_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:scifirpg.Faction)
    }

    static {
      defaultInstance = new Faction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:scifirpg.Faction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scifirpg_Faction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scifirpg_Faction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scifirpg_Faction_Relation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scifirpg_Faction_Relation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scifirpg_Faction_Rank_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scifirpg_Faction_Rank_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)com/eldritch/invoken/proto/factions.pr" +
      "oto\022\010scifirpg\032,com/eldritch/invoken/prot" +
      "o/disciplines.proto\"\215\002\n\007Faction\022\n\n\002id\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \002(\t\022,\n\010relation\030\003 \003(\0132\032.sc" +
      "ifirpg.Faction.Relation\022$\n\004rank\030\004 \003(\0132\026." +
      "scifirpg.Faction.Rank\022\'\n\talignment\030\005 \001(\016" +
      "2\024.scifirpg.Profession\022\026\n\007visible\030\006 \001(\010:" +
      "\005false\0320\n\010Relation\022\022\n\nfaction_id\030\001 \001(\t\022\020" +
      "\n\010reaction\030\002 \001(\005\032!\n\004Rank\022\n\n\002id\030\001 \002(\005\022\r\n\005" +
      "title\030\002 \002(\tB\034\n\032com.eldritch.invoken.prot",
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scifirpg_Faction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scifirpg_Faction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scifirpg_Faction_descriptor,
              new java.lang.String[] { "Id", "Name", "Relation", "Rank", "Alignment", "Visible", });
          internal_static_scifirpg_Faction_Relation_descriptor =
            internal_static_scifirpg_Faction_descriptor.getNestedTypes().get(0);
          internal_static_scifirpg_Faction_Relation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scifirpg_Faction_Relation_descriptor,
              new java.lang.String[] { "FactionId", "Reaction", });
          internal_static_scifirpg_Faction_Rank_descriptor =
            internal_static_scifirpg_Faction_descriptor.getNestedTypes().get(1);
          internal_static_scifirpg_Faction_Rank_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scifirpg_Faction_Rank_descriptor,
              new java.lang.String[] { "Id", "Title", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.eldritch.invoken.proto.Disciplines.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
