// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/eldritch/scifirpg/proto/missions.proto

package com.eldritch.invoken.proto;

public final class Missions {
  private Missions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MissionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .scifirpg.Mission.Stage stage = 3;
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    java.util.List<com.eldritch.invoken.proto.Missions.Mission.Stage> 
        getStageList();
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    com.eldritch.invoken.proto.Missions.Mission.Stage getStage(int index);
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    int getStageCount();
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    java.util.List<? extends com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder> 
        getStageOrBuilderList();
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder getStageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code scifirpg.Mission}
   */
  public static final class Mission extends
      com.google.protobuf.GeneratedMessage
      implements MissionOrBuilder {
    // Use Mission.newBuilder() to construct.
    private Mission(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Mission(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Mission defaultInstance;
    public static Mission getDefaultInstance() {
      return defaultInstance;
    }

    public Mission getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Mission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                stage_ = new java.util.ArrayList<com.eldritch.invoken.proto.Missions.Mission.Stage>();
                mutable_bitField0_ |= 0x00000004;
              }
              stage_.add(input.readMessage(com.eldritch.invoken.proto.Missions.Mission.Stage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          stage_ = java.util.Collections.unmodifiableList(stage_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eldritch.invoken.proto.Missions.Mission.class, com.eldritch.invoken.proto.Missions.Mission.Builder.class);
    }

    public static com.google.protobuf.Parser<Mission> PARSER =
        new com.google.protobuf.AbstractParser<Mission>() {
      public Mission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mission(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Mission> getParserForType() {
      return PARSER;
    }

    public interface StageOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 id = 1;
      /**
       * <code>required int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 1;</code>
       */
      int getId();

      // required string description = 2;
      /**
       * <code>required string description = 2;</code>
       */
      boolean hasDescription();
      /**
       * <code>required string description = 2;</code>
       */
      java.lang.String getDescription();
      /**
       * <code>required string description = 2;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();

      // required bool finished = 3 [default = false];
      /**
       * <code>required bool finished = 3 [default = false];</code>
       */
      boolean hasFinished();
      /**
       * <code>required bool finished = 3 [default = false];</code>
       */
      boolean getFinished();
    }
    /**
     * Protobuf type {@code scifirpg.Mission.Stage}
     *
     * <pre>
     * The ID of the Stage is important, because one of the rules we apply is that no outcome
     * can set a Mission stage to a previous stage.  This prevents bugs whereby a particular trigger
     * will undo progress in a mission.
     * </pre>
     */
    public static final class Stage extends
        com.google.protobuf.GeneratedMessage
        implements StageOrBuilder {
      // Use Stage.newBuilder() to construct.
      private Stage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Stage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Stage defaultInstance;
      public static Stage getDefaultInstance() {
        return defaultInstance;
      }

      public Stage getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Stage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                description_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                finished_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_Stage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_Stage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eldritch.invoken.proto.Missions.Mission.Stage.class, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder.class);
      }

      public static com.google.protobuf.Parser<Stage> PARSER =
          new com.google.protobuf.AbstractParser<Stage>() {
        public Stage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Stage(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Stage> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      // required string description = 2;
      public static final int DESCRIPTION_FIELD_NUMBER = 2;
      private java.lang.Object description_;
      /**
       * <code>required string description = 2;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required bool finished = 3 [default = false];
      public static final int FINISHED_FIELD_NUMBER = 3;
      private boolean finished_;
      /**
       * <code>required bool finished = 3 [default = false];</code>
       */
      public boolean hasFinished() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool finished = 3 [default = false];</code>
       */
      public boolean getFinished() {
        return finished_;
      }

      private void initFields() {
        id_ = 0;
        description_ = "";
        finished_ = false;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDescription()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFinished()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getDescriptionBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBool(3, finished_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getDescriptionBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, finished_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.eldritch.invoken.proto.Missions.Mission.Stage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.eldritch.invoken.proto.Missions.Mission.Stage prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code scifirpg.Mission.Stage}
       *
       * <pre>
       * The ID of the Stage is important, because one of the rules we apply is that no outcome
       * can set a Mission stage to a previous stage.  This prevents bugs whereby a particular trigger
       * will undo progress in a mission.
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_Stage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_Stage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.eldritch.invoken.proto.Missions.Mission.Stage.class, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder.class);
        }

        // Construct using com.eldritch.scifirpg.proto.Missions.Mission.Stage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          description_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          finished_ = false;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_Stage_descriptor;
        }

        public com.eldritch.invoken.proto.Missions.Mission.Stage getDefaultInstanceForType() {
          return com.eldritch.invoken.proto.Missions.Mission.Stage.getDefaultInstance();
        }

        public com.eldritch.invoken.proto.Missions.Mission.Stage build() {
          com.eldritch.invoken.proto.Missions.Mission.Stage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.eldritch.invoken.proto.Missions.Mission.Stage buildPartial() {
          com.eldritch.invoken.proto.Missions.Mission.Stage result = new com.eldritch.invoken.proto.Missions.Mission.Stage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.description_ = description_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.finished_ = finished_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.eldritch.invoken.proto.Missions.Mission.Stage) {
            return mergeFrom((com.eldritch.invoken.proto.Missions.Mission.Stage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.eldritch.invoken.proto.Missions.Mission.Stage other) {
          if (other == com.eldritch.invoken.proto.Missions.Mission.Stage.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasDescription()) {
            bitField0_ |= 0x00000002;
            description_ = other.description_;
            onChanged();
          }
          if (other.hasFinished()) {
            setFinished(other.getFinished());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasDescription()) {
            
            return false;
          }
          if (!hasFinished()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.eldritch.invoken.proto.Missions.Mission.Stage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.eldritch.invoken.proto.Missions.Mission.Stage) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 id = 1;
        private int id_ ;
        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        // required string description = 2;
        private java.lang.Object description_ = "";
        /**
         * <code>required string description = 2;</code>
         */
        public boolean hasDescription() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string description = 2;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string description = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string description = 2;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string description = 2;</code>
         */
        public Builder clearDescription() {
          bitField0_ = (bitField0_ & ~0x00000002);
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <code>required string description = 2;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          description_ = value;
          onChanged();
          return this;
        }

        // required bool finished = 3 [default = false];
        private boolean finished_ ;
        /**
         * <code>required bool finished = 3 [default = false];</code>
         */
        public boolean hasFinished() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bool finished = 3 [default = false];</code>
         */
        public boolean getFinished() {
          return finished_;
        }
        /**
         * <code>required bool finished = 3 [default = false];</code>
         */
        public Builder setFinished(boolean value) {
          bitField0_ |= 0x00000004;
          finished_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool finished = 3 [default = false];</code>
         */
        public Builder clearFinished() {
          bitField0_ = (bitField0_ & ~0x00000004);
          finished_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:scifirpg.Mission.Stage)
      }

      static {
        defaultInstance = new Stage(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:scifirpg.Mission.Stage)
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * unique key
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .scifirpg.Mission.Stage stage = 3;
    public static final int STAGE_FIELD_NUMBER = 3;
    private java.util.List<com.eldritch.invoken.proto.Missions.Mission.Stage> stage_;
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    public java.util.List<com.eldritch.invoken.proto.Missions.Mission.Stage> getStageList() {
      return stage_;
    }
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    public java.util.List<? extends com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder> 
        getStageOrBuilderList() {
      return stage_;
    }
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    public int getStageCount() {
      return stage_.size();
    }
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    public com.eldritch.invoken.proto.Missions.Mission.Stage getStage(int index) {
      return stage_.get(index);
    }
    /**
     * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
     */
    public com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder getStageOrBuilder(
        int index) {
      return stage_.get(index);
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      stage_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getStageCount(); i++) {
        if (!getStage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < stage_.size(); i++) {
        output.writeMessage(3, stage_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < stage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, stage_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eldritch.invoken.proto.Missions.Mission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eldritch.invoken.proto.Missions.Mission prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scifirpg.Mission}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eldritch.invoken.proto.Missions.MissionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eldritch.invoken.proto.Missions.Mission.class, com.eldritch.invoken.proto.Missions.Mission.Builder.class);
      }

      // Construct using com.eldritch.scifirpg.proto.Missions.Mission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (stageBuilder_ == null) {
          stage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          stageBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eldritch.invoken.proto.Missions.internal_static_scifirpg_Mission_descriptor;
      }

      public com.eldritch.invoken.proto.Missions.Mission getDefaultInstanceForType() {
        return com.eldritch.invoken.proto.Missions.Mission.getDefaultInstance();
      }

      public com.eldritch.invoken.proto.Missions.Mission build() {
        com.eldritch.invoken.proto.Missions.Mission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eldritch.invoken.proto.Missions.Mission buildPartial() {
        com.eldritch.invoken.proto.Missions.Mission result = new com.eldritch.invoken.proto.Missions.Mission(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (stageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            stage_ = java.util.Collections.unmodifiableList(stage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.stage_ = stage_;
        } else {
          result.stage_ = stageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eldritch.invoken.proto.Missions.Mission) {
          return mergeFrom((com.eldritch.invoken.proto.Missions.Mission)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eldritch.invoken.proto.Missions.Mission other) {
        if (other == com.eldritch.invoken.proto.Missions.Mission.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (stageBuilder_ == null) {
          if (!other.stage_.isEmpty()) {
            if (stage_.isEmpty()) {
              stage_ = other.stage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureStageIsMutable();
              stage_.addAll(other.stage_);
            }
            onChanged();
          }
        } else {
          if (!other.stage_.isEmpty()) {
            if (stageBuilder_.isEmpty()) {
              stageBuilder_.dispose();
              stageBuilder_ = null;
              stage_ = other.stage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              stageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStageFieldBuilder() : null;
            } else {
              stageBuilder_.addAllMessages(other.stage_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getStageCount(); i++) {
          if (!getStage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eldritch.invoken.proto.Missions.Mission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eldritch.invoken.proto.Missions.Mission) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * unique key
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .scifirpg.Mission.Stage stage = 3;
      private java.util.List<com.eldritch.invoken.proto.Missions.Mission.Stage> stage_ =
        java.util.Collections.emptyList();
      private void ensureStageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stage_ = new java.util.ArrayList<com.eldritch.invoken.proto.Missions.Mission.Stage>(stage_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.eldritch.invoken.proto.Missions.Mission.Stage, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder, com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder> stageBuilder_;

      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public java.util.List<com.eldritch.invoken.proto.Missions.Mission.Stage> getStageList() {
        if (stageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stage_);
        } else {
          return stageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public int getStageCount() {
        if (stageBuilder_ == null) {
          return stage_.size();
        } else {
          return stageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public com.eldritch.invoken.proto.Missions.Mission.Stage getStage(int index) {
        if (stageBuilder_ == null) {
          return stage_.get(index);
        } else {
          return stageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder setStage(
          int index, com.eldritch.invoken.proto.Missions.Mission.Stage value) {
        if (stageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStageIsMutable();
          stage_.set(index, value);
          onChanged();
        } else {
          stageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder setStage(
          int index, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder builderForValue) {
        if (stageBuilder_ == null) {
          ensureStageIsMutable();
          stage_.set(index, builderForValue.build());
          onChanged();
        } else {
          stageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder addStage(com.eldritch.invoken.proto.Missions.Mission.Stage value) {
        if (stageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStageIsMutable();
          stage_.add(value);
          onChanged();
        } else {
          stageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder addStage(
          int index, com.eldritch.invoken.proto.Missions.Mission.Stage value) {
        if (stageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStageIsMutable();
          stage_.add(index, value);
          onChanged();
        } else {
          stageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder addStage(
          com.eldritch.invoken.proto.Missions.Mission.Stage.Builder builderForValue) {
        if (stageBuilder_ == null) {
          ensureStageIsMutable();
          stage_.add(builderForValue.build());
          onChanged();
        } else {
          stageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder addStage(
          int index, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder builderForValue) {
        if (stageBuilder_ == null) {
          ensureStageIsMutable();
          stage_.add(index, builderForValue.build());
          onChanged();
        } else {
          stageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder addAllStage(
          java.lang.Iterable<? extends com.eldritch.invoken.proto.Missions.Mission.Stage> values) {
        if (stageBuilder_ == null) {
          ensureStageIsMutable();
          super.addAll(values, stage_);
          onChanged();
        } else {
          stageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder clearStage() {
        if (stageBuilder_ == null) {
          stage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          stageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public Builder removeStage(int index) {
        if (stageBuilder_ == null) {
          ensureStageIsMutable();
          stage_.remove(index);
          onChanged();
        } else {
          stageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public com.eldritch.invoken.proto.Missions.Mission.Stage.Builder getStageBuilder(
          int index) {
        return getStageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder getStageOrBuilder(
          int index) {
        if (stageBuilder_ == null) {
          return stage_.get(index);  } else {
          return stageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public java.util.List<? extends com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder> 
           getStageOrBuilderList() {
        if (stageBuilder_ != null) {
          return stageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stage_);
        }
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public com.eldritch.invoken.proto.Missions.Mission.Stage.Builder addStageBuilder() {
        return getStageFieldBuilder().addBuilder(
            com.eldritch.invoken.proto.Missions.Mission.Stage.getDefaultInstance());
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public com.eldritch.invoken.proto.Missions.Mission.Stage.Builder addStageBuilder(
          int index) {
        return getStageFieldBuilder().addBuilder(
            index, com.eldritch.invoken.proto.Missions.Mission.Stage.getDefaultInstance());
      }
      /**
       * <code>repeated .scifirpg.Mission.Stage stage = 3;</code>
       */
      public java.util.List<com.eldritch.invoken.proto.Missions.Mission.Stage.Builder> 
           getStageBuilderList() {
        return getStageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.eldritch.invoken.proto.Missions.Mission.Stage, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder, com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder> 
          getStageFieldBuilder() {
        if (stageBuilder_ == null) {
          stageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.eldritch.invoken.proto.Missions.Mission.Stage, com.eldritch.invoken.proto.Missions.Mission.Stage.Builder, com.eldritch.invoken.proto.Missions.Mission.StageOrBuilder>(
                  stage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          stage_ = null;
        }
        return stageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:scifirpg.Mission)
    }

    static {
      defaultInstance = new Mission(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:scifirpg.Mission)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scifirpg_Mission_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scifirpg_Mission_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scifirpg_Mission_Stage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scifirpg_Mission_Stage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*com/eldritch/scifirpg/proto/missions.p" +
      "roto\022\010scifirpg\"\216\001\n\007Mission\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \002(\t\022&\n\005stage\030\003 \003(\0132\027.scifirpg.M" +
      "ission.Stage\032A\n\005Stage\022\n\n\002id\030\001 \002(\005\022\023\n\013des" +
      "cription\030\002 \002(\t\022\027\n\010finished\030\003 \002(\010:\005falseB" +
      "\035\n\033com.eldritch.scifirpg.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scifirpg_Mission_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scifirpg_Mission_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scifirpg_Mission_descriptor,
              new java.lang.String[] { "Id", "Name", "Stage", });
          internal_static_scifirpg_Mission_Stage_descriptor =
            internal_static_scifirpg_Mission_descriptor.getNestedTypes().get(0);
          internal_static_scifirpg_Mission_Stage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scifirpg_Mission_Stage_descriptor,
              new java.lang.String[] { "Id", "Description", "Finished", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
