// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/eldritch/invoken/proto/outcomes.proto

package com.eldritch.invoken.proto;

public final class Outcomes {
  private Outcomes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OutcomeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double weight = 1 [default = 1];
    /**
     * <code>required double weight = 1 [default = 1];</code>
     *
     * <pre>
     * 0.0 -&gt; 1.0
     * </pre>
     */
    boolean hasWeight();
    /**
     * <code>required double weight = 1 [default = 1];</code>
     *
     * <pre>
     * 0.0 -&gt; 1.0
     * </pre>
     */
    double getWeight();

    // required .scifirpg.Outcome.Type type = 2;
    /**
     * <code>required .scifirpg.Outcome.Type type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .scifirpg.Outcome.Type type = 2;</code>
     */
    com.eldritch.invoken.proto.Outcomes.Outcome.Type getType();

    // optional string target = 3;
    /**
     * <code>optional string target = 3;</code>
     */
    boolean hasTarget();
    /**
     * <code>optional string target = 3;</code>
     */
    java.lang.String getTarget();
    /**
     * <code>optional string target = 3;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    // optional int32 value = 4;
    /**
     * <code>optional int32 value = 4;</code>
     */
    boolean hasValue();
    /**
     * <code>optional int32 value = 4;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code scifirpg.Outcome}
   */
  public static final class Outcome extends
      com.google.protobuf.GeneratedMessage
      implements OutcomeOrBuilder {
    // Use Outcome.newBuilder() to construct.
    private Outcome(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Outcome(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Outcome defaultInstance;
    public static Outcome getDefaultInstance() {
      return defaultInstance;
    }

    public Outcome getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Outcome(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              weight_ = input.readDouble();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.eldritch.invoken.proto.Outcomes.Outcome.Type value = com.eldritch.invoken.proto.Outcomes.Outcome.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              target_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eldritch.invoken.proto.Outcomes.internal_static_scifirpg_Outcome_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eldritch.invoken.proto.Outcomes.internal_static_scifirpg_Outcome_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eldritch.invoken.proto.Outcomes.Outcome.class, com.eldritch.invoken.proto.Outcomes.Outcome.Builder.class);
    }

    public static com.google.protobuf.Parser<Outcome> PARSER =
        new com.google.protobuf.AbstractParser<Outcome>() {
      public Outcome parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Outcome(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Outcome> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code scifirpg.Outcome.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ITEM_CHANGE = 0;</code>
       *
       * <pre>
       * NOTE: if removing an equipped item would drop the count to 0, it will also be unequipped
       * </pre>
       */
      ITEM_CHANGE(0, 0),
      /**
       * <code>REP_CHANGE = 1;</code>
       *
       * <pre>
       * COUNT reputation with TARGET faction
       * </pre>
       */
      REP_CHANGE(1, 1),
      /**
       * <code>XP_GAIN = 2;</code>
       *
       * <pre>
       * COUNT experience points for TARGET discipline
       * </pre>
       */
      XP_GAIN(2, 2),
      /**
       * <code>AUG_USE = 3;</code>
       *
       * <pre>
       * COUNT uses of TARGET augmentation
       * </pre>
       */
      AUG_USE(3, 3),
      /**
       * <code>AUG_GAIN = 4;</code>
       *
       * <pre>
       * TARGET augmentation added to inventory
       * </pre>
       */
      AUG_GAIN(4, 4),
      /**
       * <code>TELEPORT = 5;</code>
       *
       * <pre>
       * TARGET destination
       * </pre>
       */
      TELEPORT(5, 5),
      /**
       * <code>NEXT_ENCOUNTER = 16;</code>
       *
       * <pre>
       * Set successor encounter
       * </pre>
       */
      NEXT_ENCOUNTER(6, 16),
      /**
       * <code>HP_CHANGE = 6;</code>
       *
       * <pre>
       * COUNT change in player health
       * </pre>
       */
      HP_CHANGE(7, 6),
      /**
       * <code>MISSION_SET = 9;</code>
       *
       * <pre>
       * Set mission stage to TARGET
       * </pre>
       */
      MISSION_SET(8, 9),
      /**
       * <code>INFLUENCE_MOD = 7;</code>
       *
       * <pre>
       * Dialogue
       * </pre>
       */
      INFLUENCE_MOD(9, 7),
      /**
       * <code>INFLUENCE_RESET = 8;</code>
       *
       * <pre>
       * Reset dialogue disposition variable to its initial state
       * </pre>
       */
      INFLUENCE_RESET(10, 8),
      /**
       * <code>START_COMBAT = 10;</code>
       *
       * <pre>
       * Only applies to dialogue in actor encounter
       * </pre>
       */
      START_COMBAT(11, 10),
      /**
       * <code>ADD_MARKER = 11;</code>
       *
       * <pre>
       * Add and remove state markers for tracking the state of specific events.
       * </pre>
       */
      ADD_MARKER(12, 11),
      /**
       * <code>REMOVE_MARKER = 12;</code>
       *
       * <pre>
       * value of -1 means remove all such markers
       * </pre>
       */
      REMOVE_MARKER(13, 12),
      /**
       * <code>KILL = 13;</code>
       *
       * <pre>
       * Kill the TARGET actor
       * </pre>
       */
      KILL(14, 13),
      /**
       * <code>GAIN_FOLLOWER = 14;</code>
       */
      GAIN_FOLLOWER(15, 14),
      /**
       * <code>LOSE_FOLLOWER = 15;</code>
       */
      LOSE_FOLLOWER(16, 15),
      ;

      /**
       * <code>ITEM_CHANGE = 0;</code>
       *
       * <pre>
       * NOTE: if removing an equipped item would drop the count to 0, it will also be unequipped
       * </pre>
       */
      public static final int ITEM_CHANGE_VALUE = 0;
      /**
       * <code>REP_CHANGE = 1;</code>
       *
       * <pre>
       * COUNT reputation with TARGET faction
       * </pre>
       */
      public static final int REP_CHANGE_VALUE = 1;
      /**
       * <code>XP_GAIN = 2;</code>
       *
       * <pre>
       * COUNT experience points for TARGET discipline
       * </pre>
       */
      public static final int XP_GAIN_VALUE = 2;
      /**
       * <code>AUG_USE = 3;</code>
       *
       * <pre>
       * COUNT uses of TARGET augmentation
       * </pre>
       */
      public static final int AUG_USE_VALUE = 3;
      /**
       * <code>AUG_GAIN = 4;</code>
       *
       * <pre>
       * TARGET augmentation added to inventory
       * </pre>
       */
      public static final int AUG_GAIN_VALUE = 4;
      /**
       * <code>TELEPORT = 5;</code>
       *
       * <pre>
       * TARGET destination
       * </pre>
       */
      public static final int TELEPORT_VALUE = 5;
      /**
       * <code>NEXT_ENCOUNTER = 16;</code>
       *
       * <pre>
       * Set successor encounter
       * </pre>
       */
      public static final int NEXT_ENCOUNTER_VALUE = 16;
      /**
       * <code>HP_CHANGE = 6;</code>
       *
       * <pre>
       * COUNT change in player health
       * </pre>
       */
      public static final int HP_CHANGE_VALUE = 6;
      /**
       * <code>MISSION_SET = 9;</code>
       *
       * <pre>
       * Set mission stage to TARGET
       * </pre>
       */
      public static final int MISSION_SET_VALUE = 9;
      /**
       * <code>INFLUENCE_MOD = 7;</code>
       *
       * <pre>
       * Dialogue
       * </pre>
       */
      public static final int INFLUENCE_MOD_VALUE = 7;
      /**
       * <code>INFLUENCE_RESET = 8;</code>
       *
       * <pre>
       * Reset dialogue disposition variable to its initial state
       * </pre>
       */
      public static final int INFLUENCE_RESET_VALUE = 8;
      /**
       * <code>START_COMBAT = 10;</code>
       *
       * <pre>
       * Only applies to dialogue in actor encounter
       * </pre>
       */
      public static final int START_COMBAT_VALUE = 10;
      /**
       * <code>ADD_MARKER = 11;</code>
       *
       * <pre>
       * Add and remove state markers for tracking the state of specific events.
       * </pre>
       */
      public static final int ADD_MARKER_VALUE = 11;
      /**
       * <code>REMOVE_MARKER = 12;</code>
       *
       * <pre>
       * value of -1 means remove all such markers
       * </pre>
       */
      public static final int REMOVE_MARKER_VALUE = 12;
      /**
       * <code>KILL = 13;</code>
       *
       * <pre>
       * Kill the TARGET actor
       * </pre>
       */
      public static final int KILL_VALUE = 13;
      /**
       * <code>GAIN_FOLLOWER = 14;</code>
       */
      public static final int GAIN_FOLLOWER_VALUE = 14;
      /**
       * <code>LOSE_FOLLOWER = 15;</code>
       */
      public static final int LOSE_FOLLOWER_VALUE = 15;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return ITEM_CHANGE;
          case 1: return REP_CHANGE;
          case 2: return XP_GAIN;
          case 3: return AUG_USE;
          case 4: return AUG_GAIN;
          case 5: return TELEPORT;
          case 16: return NEXT_ENCOUNTER;
          case 6: return HP_CHANGE;
          case 9: return MISSION_SET;
          case 7: return INFLUENCE_MOD;
          case 8: return INFLUENCE_RESET;
          case 10: return START_COMBAT;
          case 11: return ADD_MARKER;
          case 12: return REMOVE_MARKER;
          case 13: return KILL;
          case 14: return GAIN_FOLLOWER;
          case 15: return LOSE_FOLLOWER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Outcomes.Outcome.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:scifirpg.Outcome.Type)
    }

    private int bitField0_;
    // required double weight = 1 [default = 1];
    public static final int WEIGHT_FIELD_NUMBER = 1;
    private double weight_;
    /**
     * <code>required double weight = 1 [default = 1];</code>
     *
     * <pre>
     * 0.0 -&gt; 1.0
     * </pre>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double weight = 1 [default = 1];</code>
     *
     * <pre>
     * 0.0 -&gt; 1.0
     * </pre>
     */
    public double getWeight() {
      return weight_;
    }

    // required .scifirpg.Outcome.Type type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.eldritch.invoken.proto.Outcomes.Outcome.Type type_;
    /**
     * <code>required .scifirpg.Outcome.Type type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .scifirpg.Outcome.Type type = 2;</code>
     */
    public com.eldritch.invoken.proto.Outcomes.Outcome.Type getType() {
      return type_;
    }

    // optional string target = 3;
    public static final int TARGET_FIELD_NUMBER = 3;
    private java.lang.Object target_;
    /**
     * <code>optional string target = 3;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string target = 3;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string target = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 value = 4;
    public static final int VALUE_FIELD_NUMBER = 4;
    private int value_;
    /**
     * <code>optional int32 value = 4;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 value = 4;</code>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      weight_ = 1D;
      type_ = com.eldritch.invoken.proto.Outcomes.Outcome.Type.ITEM_CHANGE;
      target_ = "";
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, weight_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTargetBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, weight_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTargetBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eldritch.invoken.proto.Outcomes.Outcome parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eldritch.invoken.proto.Outcomes.Outcome prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scifirpg.Outcome}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eldritch.invoken.proto.Outcomes.OutcomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eldritch.invoken.proto.Outcomes.internal_static_scifirpg_Outcome_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eldritch.invoken.proto.Outcomes.internal_static_scifirpg_Outcome_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eldritch.invoken.proto.Outcomes.Outcome.class, com.eldritch.invoken.proto.Outcomes.Outcome.Builder.class);
      }

      // Construct using com.eldritch.invoken.proto.Outcomes.Outcome.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        weight_ = 1D;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.eldritch.invoken.proto.Outcomes.Outcome.Type.ITEM_CHANGE;
        bitField0_ = (bitField0_ & ~0x00000002);
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eldritch.invoken.proto.Outcomes.internal_static_scifirpg_Outcome_descriptor;
      }

      public com.eldritch.invoken.proto.Outcomes.Outcome getDefaultInstanceForType() {
        return com.eldritch.invoken.proto.Outcomes.Outcome.getDefaultInstance();
      }

      public com.eldritch.invoken.proto.Outcomes.Outcome build() {
        com.eldritch.invoken.proto.Outcomes.Outcome result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eldritch.invoken.proto.Outcomes.Outcome buildPartial() {
        com.eldritch.invoken.proto.Outcomes.Outcome result = new com.eldritch.invoken.proto.Outcomes.Outcome(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.weight_ = weight_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eldritch.invoken.proto.Outcomes.Outcome) {
          return mergeFrom((com.eldritch.invoken.proto.Outcomes.Outcome)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eldritch.invoken.proto.Outcomes.Outcome other) {
        if (other == com.eldritch.invoken.proto.Outcomes.Outcome.getDefaultInstance()) return this;
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTarget()) {
          bitField0_ |= 0x00000004;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWeight()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eldritch.invoken.proto.Outcomes.Outcome parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eldritch.invoken.proto.Outcomes.Outcome) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double weight = 1 [default = 1];
      private double weight_ = 1D;
      /**
       * <code>required double weight = 1 [default = 1];</code>
       *
       * <pre>
       * 0.0 -&gt; 1.0
       * </pre>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double weight = 1 [default = 1];</code>
       *
       * <pre>
       * 0.0 -&gt; 1.0
       * </pre>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>required double weight = 1 [default = 1];</code>
       *
       * <pre>
       * 0.0 -&gt; 1.0
       * </pre>
       */
      public Builder setWeight(double value) {
        bitField0_ |= 0x00000001;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double weight = 1 [default = 1];</code>
       *
       * <pre>
       * 0.0 -&gt; 1.0
       * </pre>
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000001);
        weight_ = 1D;
        onChanged();
        return this;
      }

      // required .scifirpg.Outcome.Type type = 2;
      private com.eldritch.invoken.proto.Outcomes.Outcome.Type type_ = com.eldritch.invoken.proto.Outcomes.Outcome.Type.ITEM_CHANGE;
      /**
       * <code>required .scifirpg.Outcome.Type type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .scifirpg.Outcome.Type type = 2;</code>
       */
      public com.eldritch.invoken.proto.Outcomes.Outcome.Type getType() {
        return type_;
      }
      /**
       * <code>required .scifirpg.Outcome.Type type = 2;</code>
       */
      public Builder setType(com.eldritch.invoken.proto.Outcomes.Outcome.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .scifirpg.Outcome.Type type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.eldritch.invoken.proto.Outcomes.Outcome.Type.ITEM_CHANGE;
        onChanged();
        return this;
      }

      // optional string target = 3;
      private java.lang.Object target_ = "";
      /**
       * <code>optional string target = 3;</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string target = 3;</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string target = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string target = 3;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string target = 3;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000004);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>optional string target = 3;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }

      // optional int32 value = 4;
      private int value_ ;
      /**
       * <code>optional int32 value = 4;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 value = 4;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 4;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 value = 4;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:scifirpg.Outcome)
    }

    static {
      defaultInstance = new Outcome(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:scifirpg.Outcome)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scifirpg_Outcome_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scifirpg_Outcome_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)com/eldritch/invoken/proto/outcomes.pr" +
      "oto\022\010scifirpg\"\202\003\n\007Outcome\022\021\n\006weight\030\001 \002(" +
      "\001:\0011\022$\n\004type\030\002 \002(\0162\026.scifirpg.Outcome.Ty" +
      "pe\022\016\n\006target\030\003 \001(\t\022\r\n\005value\030\004 \001(\005\"\236\002\n\004Ty" +
      "pe\022\017\n\013ITEM_CHANGE\020\000\022\016\n\nREP_CHANGE\020\001\022\013\n\007X" +
      "P_GAIN\020\002\022\013\n\007AUG_USE\020\003\022\014\n\010AUG_GAIN\020\004\022\014\n\010T" +
      "ELEPORT\020\005\022\022\n\016NEXT_ENCOUNTER\020\020\022\r\n\tHP_CHAN" +
      "GE\020\006\022\017\n\013MISSION_SET\020\t\022\021\n\rINFLUENCE_MOD\020\007" +
      "\022\023\n\017INFLUENCE_RESET\020\010\022\020\n\014START_COMBAT\020\n\022" +
      "\016\n\nADD_MARKER\020\013\022\021\n\rREMOVE_MARKER\020\014\022\010\n\004KI",
      "LL\020\r\022\021\n\rGAIN_FOLLOWER\020\016\022\021\n\rLOSE_FOLLOWER" +
      "\020\017B\034\n\032com.eldritch.invoken.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scifirpg_Outcome_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scifirpg_Outcome_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scifirpg_Outcome_descriptor,
              new java.lang.String[] { "Weight", "Type", "Target", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
